### PR TITLE
Fix Incompatibility with TopRoleEverywhere + Compact Mode

### PR DESCRIPTION
**Pull request by xchatiii**
The theme is incompatible with [TopRoleEverywhere](https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/TopRoleEverywhere/), which produces something like this:

image

### CODE REVIEW

**Comment by xchatiii** [comment]
As a side note, the theme will immediately work with this custom css snippet:
```
/* incompatibility with TopRoleEverywhere */
.headerText-2z4IhQ > .role-2TIOKu {
    display: inline-table;
    padding-right: 8px;
}
```

**Comment by NyxIsBad** [comment]
I've tested this and it seems to make it worse? This is without pr https://i.imgur.com/F5l9sD6.jpg
This is with https://i.imgur.com/fI8uEF4.png
@xchatiii intended or do you have different results?

**Comment by xchatiii** [comment]
Oh, I was using compact mode and it looked very bad with it.
I guess I'm a very fringe user then :P

**Comment by xchatiii** [comment]
I guess this pull request isn't as necessary as others then.
It's not everyday that someone random is using a compact mode and in addition using one very certain plugin out of the hundreds floating around. Close if the team wishes.

**Comment by NyxIsBad** [comment]
Ohh, I see, compact mode. I think that we'll close it, running your PR with compact mode I get:
Before: https://i.imgur.com/9eWfRcD.png
After: https://i.imgur.com/4UhiHzH.png
which once again looks odd. If you're having some weird issue with compact mode, you can try dming me. I can't seem to reproduce toproleeverywhere looking weird on compact mode, so I wonder if maybe there's a secondary plugin conflict here?

**Comment by xchatiii** [comment]
Of course it looks bad with the unfixed version; I have already compiled and am using the fixed version.
Anyways, thanks for your attention.

**Pull request closed without merging**
