### PR TITLE
Fixes for apps popout and security key list

### PR DESCRIPTION
**Pull request by J-Emil-P**
Since this is my first commit to something that uses SCSS, I would recommend reading it fully or test it before merging.

https://discord.com/channels/212324635356692500/858733936800956427/1270769660039663636
https://discord.com/channels/212324635356692500/858733936800956427/1270815649417007175

### CODE REVIEW

**Comment by BabyBoySnow** [comment]
I would recommend using calc if it doesn't interfere with anything. Eg `background-color: rgba(0, 0, 0, calc(var--background-shading) * 0.3)`

**Comment by J-Emil-P** [comment]
> `background-color: rgba(0, 0, 0, calc(var--background-shading) * 0.3))`

Not to be that guy but it is kind of funny that you wrote something correctly and then edited it to be wrong, at least it looks wrong (two opening brackets with three closing brackets)

regrading the comment, I'll test

**Comment by BabyBoySnow** [comment]
> > `background-color: rgba(0, 0, 0, calc(var--background-shading) * 0.3))`
> 
> Not to be that guy but it is kind of funny that you wrote something correctly and then edited it to be wrong, at least it looks wrong (two opening brackets with three closing brackets)
> 
> regrading the comment, I'll test

The first one wasn't right, it needs three, one for calc, one for car and one for rgba lol

**Comment by J-Emil-P** [comment]
Don't merge, found an issue

**Comment by J-Emil-P** [comment]
> Don't merge, found an issue

Fixed the issue

**Comment by BabyBoySnow** [comment]
Did you test for 0% shading to see how that looks?

**Comment by J-Emil-P** [comment]
Yes I did but there is a little detail that I am unsure of
Should it look like this
trending apps 1
or this?
trending apps 2
(at 0% shading)

**Comment by BabyBoySnow** [comment]
> Yes I did but there is a little detail that I am unsure of Should it look like this trending apps 1 or this? trending apps 2 (at 0% shading)
> 
> I am asking since the unrounded corners makes it feel kind of odd

The first one looks better to me with it being more centered but maybe that's a screenshot issue?

**Comment by J-Emil-P** [comment]
The centering is just a screenshot issue, the only change is the gray under the banner image

**Comment by J-Emil-P** [comment]
This is how it currently looks with 100% shading

https://github.com/user-attachments/assets/4a484806-db4f-48a6-aedc-6f29104f991f

And with 0% shading

https://github.com/user-attachments/assets/9863da79-226b-4ff6-9d6f-2f8405a68ddb

If it looks good and does not have any issues feel free to merge

**Pull request merged**
